### ISSUE TITLE
The Japanese text encoding is broken.

### ISSUE THREAD

**Issue by suikan4github** [minoue-xx/Livescript2markdown#17]
## Overview
The text encoding of the  [function/private/processincludegraphics.m](https://github.com/minoue-xx/livescript2markdown/blob/6bad945ae09ed8679e91f1f6afdca6e812d27984/function/private/processincludegraphics.m#L17)
is broken. Neither UTF8, SJIS nor EUC can decode the Japanese text in this file.

Also, some files are encoded by UTF-8, some files are encoded by SJIS. Note that both develop and master have the same problem.

## Investigated files
BROKEN : 
- [function/private/processincludegraphics.m](https://github.com/minoue-xx/livescript2markdown/blob/6bad945ae09ed8679e91f1f6afdca6e812d27984/function/private/processincludegraphics.m#L17)

UTF8 :
- function/latex2markdown.m

SJIS : 
- function/private/mergeSameEnvironments.m
- function/private/processDocumentOutput.m
- function/private/processEquations.m
- function/private/processLiteralOutput.m

## Suggested fix
At least [function/private/processincludegraphics.m](https://github.com/minoue-xx/livescript2markdown/blob/6bad945ae09ed8679e91f1f6afdca6e812d27984/function/private/processincludegraphics.m#L17) should be fixed. 

Other files might be better to align as UTF8 encoding, which is the default of the Matlab.

**Comment by minoue-xx** [comment]
Thank you very much for the comments and suggestions.

The default encoding for Japanese was changed to UFT-8 starting R2020a and I will make other files align as UTF8 encoding.

**Comment by minoue-xx** [comment]
Updated the encoding to UTF-8.

- function/private/mergeSameEnvironments.m
- function/private/processDocumentOutput.m
- function/private/processEquations.m
- function/private/processLiteralOutput.m

Thanks for raising the issue! I appreciate it.
