### ISSUE TITLE
latex math function nonconvertable

### ISSUE THREAD

**Issue by mustafaakbas** [minoue-xx/Livescript2markdown#19]
in Matlab live editor, there are three ways to wite equations;
First: by using Matlab editor insert math structures, symbols
Second: by writing standard keyboard characters
Third: using LaTex format ( \theta)

If we write first way It can be convertible to MD but LaTex equation cant convert to MD

**Comment by minoue-xx** [comment]
Yes, the equations by the two input methods available on the Live Editor (Ctrl+Shift+E or Ctrl+Shift+L) only will be converted to MD.
