### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by KentaItakura** [minoue-xx/Livescript2markdown#22]
Is is possible to export "table of contents" as markdown file? I would like to obtain table of contents after creating it in "insert tab".

**Comment by minoue-xx** [comment]
Thanks for your feedback. I have added an option to add a table of contents at the beginning of the generated markdown file. You do not need to add a table of contents to the original livescript. With ToC = true option will generate a table of contents regardless. 

>> latex2markdown('livescript.mlx',ToC = true);

will do the job. It would be great if you could try and let me know if it works with your livescript files.
