### ISSUE TITLE
The font size of equations after exporting to markdown

### ISSUE THREAD

**Issue by KentaItakura** [minoue-xx/Livescript2markdown#23]
Hi, thank you so much for your hard work for this repo. This repo is super helpful. 
Is it possible to change or tune the font size of equations (latex) after exporting to md file? 
I would like to write a blog post, but the font size of equations is a bit small than I expected.

**Comment by minoue-xx** [comment]
inline option begin used for the equation within the text. If you delete inline from the generate markdown file, it may increase the size of the equation. (Note: this does not apply when format=qiita is used)
