### ISSUE TITLE
Embedding formulas in markdown, https://latex.codecogs.com/ rendering prefix should removed

### ISSUE THREAD

**Issue by cuixing158** [minoue-xx/Livescript2markdown#27]
As I've learned in recent months, markdown in github already supports latex formula rendering, and the prefix “https://latex.codecogs.com/” should be removed.

**Comment by minoue-xx** [comment]
Good point. It had a format option "github_math" to use equation rendering support on GitHub as of v1.5. I just changed that to the default behavior in v2.0.
